### ISSUE TITLE
Builder does not use vendoring

### ISSUE THREAD

**Issue by bluecmd** [u-root/u-root#1024]
Hi,

When building u-bmc without an u-root checked out I get this:

```
GOARM=5 GOARCH=arm ./u-bmc -o "initramfs.cpio.tmp" -p "quanta-f06-leopard-ddr3"
2018/11/13 16:17:30 Build environment: GOARCH=arm GOOS=linux GOROOT=/usr/local/go GOPATH=/home/bluecmd/go CGO_ENABLED=0
2018/11/13 16:17:30 Filename is initramfs.cpio.tmp
2018/11/13 16:17:30 "github.com/u-root/u-root/cmds/ansi" is neither package or path/glob: cannot find package "github.com/u-root/u-root/cmds/ansi" in any of:
    /usr/local/go/src/github.com/u-root/u-root/cmds/ansi (from $GOROOT)
    /home/bluecmd/go/src/github.com/u-root/u-root/cmds/ansi (from $GOPATH)
```

Note that it does not try to look at u-bmc's vendor directory.

As a workaround I tried `ln -sf ~/go/src/github.com/u-root/u-bmc/vendor/github.com/u-root/u-root ~/go/src/github.com/u-root/u-root`, and that seems to work for now.

**Comment by bluecmd** [comment]
Actually, that ln workaround didn't work from a clean slate:

```
cmds/cmp/cmp.go:32:2: could not import github.com/rck/unit (cannot find package "github.com/rck/unit" in any of:
	/usr/local/go/src/github.com/rck/unit (from $GOROOT)
	/go/src/github.com/rck/unit (from $GOPATH))
Makefile:204: recipe for target 'initramfs.cpio' failed
```

I'll resort to not vendor the u-root cmds and "go get" it on every build for now, but that's not sustainable.

**Comment by hugelgupf** [comment]
The Go toolchain doesn't allow you to vendor commands, afaik. Since we use the Go toolchain to discover the commands during the build process, this means you have to have a local copy of all the commands you want to build.

How do you feel about #583 as a workaround?

**Comment by hugelgupf** [comment]
This is in progress with Go module support in #1358.
