### ISSUE TITLE
installcommand does not compile command when passed --help

### ISSUE THREAD

**Issue by rjoleary** [u-root/u-root#107]
When sort is not yet compiled by installcommand, the output is:
```
% sort --help
Usage of sort:
  -ludicrous
    	print out ALL the output from the go build commands
  -v	print all build commands
wait: exit status 2:
```

The expect output is:
```
% sort --help
Usage of sort:
  -o string
    	Output file
  -r	Reverse
wait: exit status 2:
```

The `flag.Parse()` statement in `installcommand` exits early. Instead, if `installcommand` is accessed through symlink, we want to proceed as normal and pass `--help` into the compiled command.

**Comment by rafaelcn** [comment]
Fixed in #521a067
