### ISSUE TITLE
wget_test.go is flaky

### ISSUE THREAD

**Issue by rjoleary** [u-root/u-root#118]
[wget_test.go](https://github.com/u-root/u-root/blob/master/cmds/wget/wget_test.go) depends on being able to connect to "http://example.com". If example.com is down or the tests are run offline, it results in a false negative.

Preferably, you would test wget by running a mini webserver on an occupied port in a separate goroutine. Access the webserver via 127.0.0.1. Only then will the test pass rain or shine.

The current build failure is a result of this flakyness: https://travis-ci.org/u-root/u-root/builds/194928679

**Comment by rminnich** [comment]
we need to remove that test entirely. It's a bad test.

**Comment by rjoleary** [comment]
Fixed by #123
