### ISSUE TITLE
ipxe logs the full pxelinux.0 binary on console.

### ISSUE THREAD

**Issue by JulienVdG** [u-root/u-root#1192]
This line logs the ipxe configuration before validating that the file is a real configuration:
https://github.com/u-root/u-root/blob/ab54e093a088e65f232bbc27a76a10609541161b/pkg/ipxe/ipxe.go#L68

I understand that for debugging it's easier to display the config before parsing it but in case it's the pxelinux.0 binary we really should not send that to the console.

RFC: do we drop the configuration print or print it only if it's valid, or find a check to discriminate binary from text ?

**Comment by rjoleary** [comment]
Fixed in #1210
