### ISSUE TITLE
Improve error message if "-files X:Y" is passed and Y is an absolute path.

### ISSUE THREAD

**Issue by srcUp** [u-root/u-root#1221]
While generating an initramfs, passing "-files /tmp/modules/:/mytmp" to u-root causes u-root binary to fail with the following error message:
```
./u-root -format=cpio -build=source  -files /tmp/modules:/mytmp -o initramfs.cpio
...<snip>...
" 2019/05/21 11:14:48 couldn't add "/tmp/modules/:/mytmp/" to archive: archive path "/mytmp" must not be absolute (host source "/tmp/modules")"
```

@rminnich asked me to file an issue so that this error message can be improved.

**Comment by rminnich** [comment]
fixed in #1224
