### ISSUE TITLE
template 'all' does not build in bb mode

### ISSUE THREAD

**Issue by jensdrenhaus** [u-root/u-root#1252]
error building: no valid `main` package files found in [/home/jens/go/src/github.com/u-root/u-root/cmds/boot/.bb/boot.go]

**Comment by hugelgupf** [comment]
Rebuild the u-root tool itself, delete all the .bb directories, and retry?

**Comment by jensdrenhaus** [comment]
Alright thanks. Thought all .bb directories were removed on rebuild, but obviously not that ones from the old directory structure.
