### ISSUE TITLE
Delete duplicate parsers for /proc/filesystems

### ISSUE THREAD

**Issue by rjoleary** [u-root/u-root#1264]
We have three parses for /proc/filesystems:

1. https://github.com/u-root/u-root/blob/master/pkg/diskboot/device.go#L26
2. https://github.com/u-root/u-root/blob/master/pkg/storage/filesystem.go#L24
3. https://github.com/u-root/u-root/blob/master/pkg/uroot/util/root_linux.go#L237

I don't see a reason to keep all three of these especially since they vary in correctness and amount of testing.

Figure out which one is worth keeping (might want to combine the best parts) and delete the other two.

**Comment by u5surf** [comment]
`fstypes()` and `storage.GetSopportedFilesystems` are almost same logic. 
It can replace `fstypes()` with `storage.GetSupportedFilesystems`.
But, `root_linux.FindFileSystem` is a little complicated than theirs. Cause it includes the if statement that removes `nodev` context.
