### ISSUE TITLE
Create yes command

### ISSUE THREAD

**Issue by upatel99** [u-root/u-root#1269]
Yes command outputs a positive response or a user-defined string infinitely until terminated or killed. An Unix command such as the yes command is a powerful tool when a user approaches a situation in which they are asked to enter "y" as yes numerously. Instead of having to type "y" multiple times, the yes command outputs the positive response until the user kills it.

**Comment by rjoleary** [comment]
Looks good. I'd suggest also implementing printing of other strings. For example:

This would print "no" an infinite number of times:
```
yes no
```

This would print "sandwich" an infinite number of times:
```
yes sandwich
```

Still make it so the default option is to print "yes" and infinite number of times.
