### ISSUE TITLE
Artifacts are sometimes not written

### ISSUE THREAD

**Issue by rjoleary** [u-root/u-root#1276]
The artifacts weren't written for this integration test:

* https://circleci.com/gh/u-root/u-root/29444#artifacts/containers/0

The artifacts include the qemu serial logs, which makes this difficult to debug.

The error message is:

```
Uploading /tmp/serial to tmp/serial
  No artifact files found at /tmp/serial
```

Compare this to this integration test where the artifacts were written successfully:

* https://circleci.com/gh/u-root/u-root/29434#artifacts/containers/0

**Comment by bjakobson** [comment]
Can it not find the artifact files within a folder or code, or is there an issue compiling it?

**Comment by rjoleary** [comment]
We just write the whole serial output to the logs now. No separate files.
