### ISSUE TITLE
cp: non-recursively copying dir should error

### ISSUE THREAD

**Issue by rjoleary** [u-root/u-root#1349]
The behaviour of the u-root's cp package seems a bit broken now.
It copies directories but none of the contents in it without any error.

$ mkdir x && touch x/a.txt
$ ./cp x y
$ ls -l y/
total 0

Instead, the cp command should error with "omitting directory y". The only way to copy directories should be with the -r flag which should also copy all the directories contents recursively.

Also, add a test.

**Comment by hugelgupf** [comment]
Fixed by #1351
