### ISSUE TITLE
Are LUKS-encrypted partitions supported?

### ISSUE THREAD

**Issue by darkdragon-001** [u-root/u-root#1492]
Are LUKS-encrypted partitions supported by `localboot` or `boot2`?

If not, including the `cryptsetup` binary with some wrapper functions as done in [9elements/tpmtool](https://github.com/9elements/tpmtool/blob/master/pkg/tpmtool/cryptsetup.go) could do the trick.

**Comment by zaolin** [comment]
Not yet. We are missing LVM, cryptsetup and devmapper support. Feel free to implement around 5000 lines of golang code for a minimal impl. Shipping in binaries in firmware isn't size efficient.
