### ISSUE TITLE
Cannot ping 127.0.0.1 or ::1

### ISSUE THREAD

**Issue by sellerie98** [u-root/u-root#1556]
Pinging 127.0.0.1 does not work:
`ping 127.0.0.1`:
```
2020/02/13 19:57:45 ping failed: bad ICMP echo reply type: 8
Exception: ping exited with 1
```
`ping -6 ::1`
```
2020/02/13 20:09:02 ping failed: bad ICMP checksum: 0 (expected 65535)
Exception: ping exited with 1
```

Also `ip l set lo up` does not fix the issue.
It does not seem to matter if an ethernet cable is connected. I use Linux 5.5.0.

**Comment by hugelgupf** [comment]
I think ping recently got a rewrite by @binjip978? Is this fixed?

**Comment by binjip978** [comment]
Somewhat fixed as I remember, for localhost it will work with -c=1 for both ipv4 and ipv6.

root@epiphyte:~/src/u-root/cmds/core/ping# ./ping -c=1 -6 ::1
64 bytes from ::1: icmp_seq=1 time=72.343µs
