### ISSUE TITLE
pkg/ulog: KernelLog initialization

### ISSUE THREAD

**Issue by jensdrenhaus** [u-root/u-root#1610]
I don't understand /pkg/ulog/klog_linux.go line 39: 
```
// Reinit reopens the /dev/kmsg file.
func (k *KLog) Reinit() {
	f, err := os.OpenFile("/dev/kmsg", os.O_RDWR, 0)
	if err != nil {
		KernelLog.File = f
	}
}
```
If os.OpenFile returns a non-nil Error, `f` allways will be nil. With this implementation `ulog.KernelLog.Print("HALLO WORLD")` has no effect in my programs.

I changed it for testing like so:
```
var x = 1

// Reinit reopens the /dev/kmsg file.
func (k *KLog) Reinit() {
	log.Printf("KLOG CALL %d", x)
	x++
	f, err := os.OpenFile("/dev/kmsg", os.O_RDWR, 0)
	if err != nil {
		log.Printf("KLOG ERROR %v %v", f, err)
		KernelLog.File = f
	}
	KernelLog.File = f
}
```
Now, `HELLO WORLD` is written to /dev/kmsg.
Further I can see that Reinit() is executed multiple times. (three times with x=1, one time with x=2 in my case)
I thought package initialization is done only once even if the package is imported many times.

Can you help me what was the initial idea with the assignment of KernelLog.File, please.

**Comment by rminnich** [comment]
I don't know what's up there but that code looks wrong to me.
Suspect it was supposed to be == nil and somebody's fingers autottype != nil

**Comment by hugelgupf** [comment]
Ron is pretty much right.

This was meant for kernels that don't automount devtmpfs, so at init() time /dev/kmsg doesn't exist yet. When you do finally mount devtmpfs in pkg/libinit, it calls this Reinit.

Seems it never worked though 🤡

Yeah, it's supposed to be `==`.

**Comment by jensdrenhaus** [comment]
okay -> #1618
