### ISSUE TITLE
CircleCI: What the heck?

### ISSUE THREAD

**Issue by ChriMarMe** [u-root/u-root#1722]
CircleCI wants to be connected to my github account now just to look at logs from failed tests? W.T.F?

**Comment by ChriMarMe** [comment]
CircleCI wants access to all my private and public repos, even if the only thing I want is to have a look at logs? Seriously...... this gets me mad

**Comment by hugelgupf** [comment]
We can do some checking around in the settings. CircleCI just changed its whole UI, perhaps there's a new setting for whether test results are public or require login.

**Comment by ChriMarMe** [comment]
That would be awesome. Thank you
