### ISSUE TITLE
pkg/checker - LinkSpeed incorrect for extremely fast interfaces

### ISSUE THREAD

**Issue by mpictor** [u-root/u-root#1737]
Noticed while looking for ethtool-related code, haven't actually tested.

at https://github.com/u-root/u-root/blob/master/pkg/checker/interfaces.go#L43
```go
		if int(eth.Speed) < minSpeed {
			return fmt.Errorf("link speed %d < %d", eth.Speed, minSpeed)
		}
```
`eth.Speed` is a uint16 and should be used in conjunction with `eth.Speed_hi`; the ethtool package calculates this and its `EthtoolCmd.CmdGet()` returns it. However, that value is thrown away by this package.

----

Also, I noticed (as of ethtool 5.4) that `struct ethtool_cmd` is deprecated and `struct ethtool_link_settings` should be used instead. The ethtool package's `EthtoolCmd` struct corresponds to ethtool_cmd. I created an issue there noting this: https://github.com/safchain/ethtool/issues/33

**Comment by mpictor** [comment]
@insomniacslk

**Comment by insomniacslk** [comment]
thank you @mpictor ! I'll look at this in my upcoming restructuring of this framework
