### ISSUE TITLE
security issues

### ISSUE THREAD

**Issue by ggkitsas** [u-root/u-root#1778]
Hi,

I'm George, part of the Snyk Security Team. We have identified some vulnerabilities in this project that we would like to further discuss. This is a follow-up of previous email communication with contributors to this project.

Looking forward to your response.

Best,
Snyk Security Team

**Comment by rminnich** [comment]
sorry george, the press of events made me fail to run your code. my memory is you found several commands. Does you tool make it practical to file one issue for each broken command?
