### ISSUE TITLE
 fix bzimage to properly parse bzimage64 into segments usable for kexec classic

### ISSUE THREAD

**Issue by orangecms** [u-root/u-root#1856]
kexec has some history and ended up with two variants. The goal is to support both.

Some hints:

https://lore.kernel.org/lkml/53E906B0.5040105@zytor.com/T/
https://github.com/xlpang/nanokexec-tools

**Comment by hugelgupf** [comment]
A basic bzimage kexec is supported in https://github.com/u-root/u-root/blob/main/pkg/boot/linux/load_linux_amd64.go
