### ISSUE TITLE
Add support for blscfg in Grub parser

### ISSUE THREAD

**Issue by insomniacslk** [u-root/u-root#1871]
`blscfg` allows using Grub to redirect to BLS for the boot configuration. We want to extend our "parser" to support scenarios like this. This requires support for flow control in Grub, hence some form of real parsing other than regexps like we currently do. This will be a bloodbath.

**Comment by rjoleary** [comment]
Would this allow us to boot CentOS 8?

**Comment by rjoleary** [comment]
There's the shell of a recursive decent parser here: https://github.com/u-root/u-root/tree/master/pkg/pogosh. A similar idea to this could be used for grub parsing.

**Comment by rjoleary** [comment]
Might be related to https://github.com/u-root/u-root/issues/1835

**Comment by hugelgupf** [comment]
We support this now, though it's probably a bit hacked up.
