### ISSUE TITLE
Add "ls" missing flags -SFf

### ISSUE THREAD

**Issue by binjip978** [u-root/u-root#1925]
Hello, from roadmap.md saw that ls is currently missing -hFfS, but seems -h is present, so i would like to add missing flags if it's still relevant, if not please close the issue.

**Comment by rjoleary** [comment]
Hi Sergei! Feel free to send us a PR to add the missing flags.

**Comment by binjip978** [comment]
added -S https://github.com/u-root/u-root/pull/2023, -F flag already implemented and WalkDir traverse files in lexical order so -f flag seems like used by default.
