### ISSUE TITLE
Update generated manpages

### ISSUE THREAD

**Issue by JohnAZoidberg** [u-root/u-root#2024]
The manpages are extracted from the comments of each command via https://github.com/u-root/u-root/blob/master/cmds/core/man/gen/gen.go and dumped into https://github.com/u-root/u-root/blob/master/cmds/core/man/data/data.go

That file hasn't been updated in 2 years so many new commands are missing and some documentation is outdated.

**Comment by rjoleary** [comment]
Maybe it would make more sense for the u-root command to re-generate the man pages at build time.

**Comment by rjoleary** [comment]
I created a separate issue for doing the automatically: #2033
