### ISSUE TITLE
page: terminal is not sane after exit

### ISSUE THREAD

**Issue by bluecmd** [u-root/u-root#2039]
Reproduce:

 1. Run `hexdump /dev/nvme0n1 | page`.
 2. Type `q` to abort
 3. Your terminal will now not have carriage return

Screenshot:
![Screenshot from 2021-06-07 11-53-39](https://user-images.githubusercontent.com/149442/120997059-32b27280-c787-11eb-8315-333320925939.png)

Git revision: 7a1f611bfd98677bc9c98d8d8941f9c6729cf813

**Comment by rjoleary** [comment]
Is `page` u-root's version of https://en.wikipedia.org/wiki/Pg_(Unix)?
