### ISSUE TITLE
Null

### ISSUE THREAD

**Issue by richiboi1977** [u-root/u-root#2131]
$got remote
origin
$git remote add on https://GitHub.com/paulboone/to git-v
origin https://GitHub.com/schacon/Paul one/ticgit (fetch)
origin https://gitHub.com/schacon/ticgit
(Push)
pb https://github.com/Shacon/paullboone/right (fetch)
pb https://GitHub.com/schacon/paulboone/tight (push)

**Comment by richiboi1977** [comment]
There I finally figured something out

**Comment by richiboi1977** [comment]
> $got remote
> origin
> $git remote add on https://GitHub.com/paulboone/to git-v
> origin https://GitHub.com/schacon/Paul one/ticgit (fetch)
> origin https://gitHub.com/schacon/ticgit
> (Push)
> pb https://github.com/Shacon/paullboone/right (fetch)
> pb https://GitHub.com/schacon/paulboone/tight (push)

**Comment by rjoleary** [comment]
What?
