### ISSUE TITLE
"localboot -grub" can't boot arm64 platforms with Centos and Ubuntu

### ISSUE THREAD

**Issue by JasonTian518** [u-root/u-root#2142]
**Describe the bug**

 Boot CentOS and Ubuntu by "localboot -grub" command on Ampere jade(linuxboot) with linuxboot,  CentOS reports "No boot configuration found",  Ubuntu reports "Exception: localboot exited with 1"

1970/01/01 00:24:05 mounted: [MountPoint(path=/mnt/nvme0n1p1, device=/dev/nvme0n1p1, fs=vfat, flags=0x1, data=) MountPoint(path=/mnt/nvme0n1p2, device=/dev/nvme0n1p2, fs=ext4, flags=0x1, data=)]
1970/01/01 00:24:05 Parsing /mnt/nvme0n1p1/EFI/centos/grub.cfg
1970/01/01 00:24:05 Parsing /mnt/nvme0n1p2/grub2/grub.cfg
1970/01/01 00:24:05 No boot configuration found
Exception: localboot exited with 1

Even Ubuntu 20.04 has menuentry after 30_0s-prober in the /boot/grub/grub.cfg, still reports below failure:
1970/01/01 00:01:39 Found 5 boot configs
1970/01/01 00:01:39   0: 'Ubuntu'
1970/01/01 00:01:39   1: 'Ubuntu, with Linux 5.4.0-88-generic'
1970/01/01 00:01:39   2: 'Ubuntu, with Linux 5.4.0-88-generic (recovery mode)'
1970/01/01 00:01:39   3: 'Ubuntu, with Linux 5.4.0-86-generic'
1970/01/01 00:01:39   4: 'Ubuntu, with Linux 5.4.0-86-generic (recovery mode)'
1970/01/01 00:01:39 Cannot open TPM: TPM device not available
1970/01/01 00:01:39 Failed to boot kernel /mnt/nvme0n1p2/vmlinuz-5.4.0-88-generic: kexec.FileLoad() failed: sys_kexec(8, 9, root=/dev/mapper/ubuntu--vg-ubuntu--lv ro, 0) = invalid argument
1970/01/01 00:01:39 Cannot open TPM: TPM device not available
1970/01/01 00:01:39 Failed to boot kernel /mnt/nvme0n1p2/vmlinuz-5.4.0-88-generic: kexec.FileLoad() failed: sys_kexec(8, 9, root=/dev/mapper/ubuntu--vg-ubuntu--lv ro, 0) = invalid argument
1970/01/01 00:01:39 Cannot open TPM: TPM device not available
1970/01/01 00:01:39 Failed to boot kernel /mnt/nvme0n1p2/vmlinuz-5.4.0-88-generic: kexec.FileLoad() failed: sys_kexec(8, 9, root=/dev/mapper/ubuntu--vg-ubuntu--lv ro recovery nomodeset, 0) = invalid argument
1970/01/01 00:01:39 Cannot open TPM: TPM device not available
1970/01/01 00:01:39 Failed to boot kernel /mnt/nvme0n1p2/vmlinuz-5.4.0-86-generic: kexec.FileLoad() failed: sys_kexec(8, 9, root=/dev/mapper/ubuntu--vg-ubuntu--lv ro, 0) = invalid argument
1970/01/01 00:01:39 Cannot open TPM: TPM device not available
1970/01/01 00:01:39 Failed to boot kernel /mnt/nvme0n1p2/vmlinuz-5.4.0-86-generic: kexec.FileLoad() failed: sys_kexec(8, 9, root=/dev/mapper/ubuntu--vg-ubuntu--lv ro recovery nomodeset, 0) = invalid argument
1970/01/01 00:01:39 No boot configuration succeeded
Exception: localboot exited with 1
[tty], line 1: localboot -grub

**To Reproduce**
1.  Build linuxboot for arm64 platforms(Ampere/jade).
2.  Prepare bootable CentOS and Ubuntu.
3.  Type "localboot -grub" after booting into linuxboot.

**Expected behavior**
1. CentOS should be bootable by "localboot -grub"
2. Ubuntu should be bootable by "localboot -grub"

**Additional context**

I compared the /boot/grub/grub.cfg, by default no menuentry from grub.cfg, I can boot CentOS 4.18/5.10 if I add below information into grub.cfg. 

	### BEGIN /etc/grub.d/30_os-prober ###
	menuentry 'CentOS Linux 8 (on /dev/mapper/cl-root)' --class centos --class gnu-linux --class gnu --class os $menuentry_id_option 'osprober-gnulinux-simple-2edb594f-6ced-449e-ba40-7cafa4e1171e' {
	        insmod part_gpt
	        insmod ext2
	        if [ x$feature_platform_search_hint = xy ]; then
	          search --no-floppy --fs-uuid --set=root  3a55a880-6c42-4b8e-8bf0-98f9f17365c4
	        else
	          search --no-floppy --fs-uuid --set=root 3a55a880-6c42-4b8e-8bf0-98f9f17365c4
	        fi
	        linux /vmlinuz-4.18.0xbtian+ root=/dev/dm-2
	        initrd /initramfs-4.18.0xbtian+.img
	}
	
If I launch OS by kexec -l xxx -i xxx -C xx/ kexec -e, all OS(CentOS with kernel 4.18, 5.10, Ubuntu 20.04) can be launched.

**Comment by JasonTian518** [comment]
Add log for Ubuntu boot by localboot -grub:
maybe it is related to TPM code. 

1970/01/01 00:16:08 mounted: [MountPoint(path=/mnt/nvme0n1p1, device=/dev/nvme0n1p1, fs=vfat, flags=0x1, data=) MountPoint(path=/mnt/nvme0n1p2, device=/dev/nvme0n1p2, fs=ext4, flags=0x1, data=)]
1970/01/01 00:16:08 Parsing /mnt/nvme0n1p1/EFI/ubuntu/grub.cfg
1970/01/01 00:16:08 Parsing /mnt/nvme0n1p2/grub/grub.cfg
1970/01/01 00:16:08 Kernel seems to be on an other partitioin then the grub.cfg file
1970/01/01 00:16:08 fs-uuid: b408daf4-c662-4810-919e-0c3c717caccd
1970/01/01 00:16:08 Kernel is on: nvme0n1p2
1970/01/01 00:16:08 Kernel seems to be on an other partitioin then the grub.cfg file
1970/01/01 00:16:08 fs-uuid: b408daf4-c662-4810-919e-0c3c717caccd
1970/01/01 00:16:08 Kernel is on: nvme0n1p2
1970/01/01 00:16:08 Kernel seems to be on an other partitioin then the grub.cfg file
1970/01/01 00:16:08 fs-uuid: b408daf4-c662-4810-919e-0c3c717caccd
1970/01/01 00:16:08 Kernel is on: nvme0n1p2
1970/01/01 00:16:08 Kernel seems to be on an other partitioin then the grub.cfg file
1970/01/01 00:16:08 fs-uuid: b408daf4-c662-4810-919e-0c3c717caccd
1970/01/01 00:16:08 Kernel is on: nvme0n1p2
1970/01/01 00:16:08 Kernel seems to be on an other partitioin then the grub.cfg file
1970/01/01 00:16:08 fs-uuid: b408daf4-c662-4810-919e-0c3c717caccd
1970/01/01 00:16:08 Kernel is on: nvme0n1p2
1970/01/01 00:16:08 Kernel seems to be on an other partitioin then the grub.cfg file
1970/01/01 00:16:08 fs-uuid: b408daf4-c662-4810-919e-0c3c717caccd
1970/01/01 00:16:08 Kernel is on: nvme0n1p2
1970/01/01 00:16:08 Kernel seems to be on an other partitioin then the grub.cfg file
1970/01/01 00:16:08 fs-uuid: b408daf4-c662-4810-919e-0c3c717caccd
1970/01/01 00:16:08 Kernel is on: nvme0n1p2
1970/01/01 00:16:08 Kernel seems to be on an other partitioin then the grub.cfg file
1970/01/01 00:16:08 fs-uuid: b408daf4-c662-4810-919e-0c3c717caccd
1970/01/01 00:16:08 Kernel is on: nvme0n1p2
1970/01/01 00:16:08 Kernel seems to be on an other partitioin then the grub.cfg file
1970/01/01 00:16:08 fs-uuid: b408daf4-c662-4810-919e-0c3c717caccd
1970/01/01 00:16:08 Kernel is on: nvme0n1p2
1970/01/01 00:16:08 Kernel seems to be on an other partitioin then the grub.cfg file
1970/01/01 00:16:08 fs-uuid: b408daf4-c662-4810-919e-0c3c717caccd
1970/01/01 00:16:08 Kernel is on: nvme0n1p2
1970/01/01 00:16:08 Found 5 boot configs
1970/01/01 00:16:08   0: 'Ubuntu'
1970/01/01 00:16:08   1: 'Ubuntu, with Linux 5.4.0-88-generic'
1970/01/01 00:16:08   2: 'Ubuntu, with Linux 5.4.0-88-generic (recovery mode)'
1970/01/01 00:16:08   3: 'Ubuntu, with Linux 5.4.0-86-generic'
1970/01/01 00:16:08   4: 'Ubuntu, with Linux 5.4.0-86-generic (recovery mode)'
1970/01/01 00:16:08 Cannot open TPM: TPM device not available
1970/01/01 00:16:08 Failed to boot kernel /mnt/nvme0n1p2/vmlinuz-5.4.0-88-generic: kexec.FileLoad() failed: sys_kexec(8, 9, root=/dev/mapper/ubuntu--vg-ubuntu--lv ro, 0) = invalid argument
1970/01/01 00:16:08 Cannot open TPM: TPM device not available
1970/01/01 00:16:08 Failed to boot kernel /mnt/nvme0n1p2/vmlinuz-5.4.0-88-generic: kexec.FileLoad() failed: sys_kexec(8, 9, root=/dev/mapper/ubuntu--vg-ubuntu--lv ro, 0) = invalid argument
1970/01/01 00:16:08 Cannot open TPM: TPM device not available
1970/01/01 00:16:08 Failed to boot kernel /mnt/nvme0n1p2/vmlinuz-5.4.0-88-generic: kexec.FileLoad() failed: sys_kexec(8, 9, root=/dev/mapper/ubuntu--vg-ubuntu--lv ro recovery nomodeset, 0) = invalid argument
1970/01/01 00:16:08 Cannot open TPM: TPM device not available
1970/01/01 00:16:08 Failed to boot kernel /mnt/nvme0n1p2/vmlinuz-5.4.0-86-generic: kexec.FileLoad() failed: sys_kexec(8, 9, root=/dev/mapper/ubuntu--vg-ubuntu--lv ro, 0) = invalid argument
1970/01/01 00:16:08 Cannot open TPM: TPM device not available
1970/01/01 00:16:08 Failed to boot kernel /mnt/nvme0n1p2/vmlinuz-5.4.0-86-generic: kexec.FileLoad() failed: sys_kexec(8, 9, root=/dev/mapper/ubuntu--vg-ubuntu--lv ro recovery nomodeset, 0) = invalid argument
1970/01/01 00:16:08 No boot configuration succeeded
Exception: localboot exited with 1
[tty], line 1: localboot -grub

**Comment by JasonTian518** [comment]
Wonder why the kernel image folder is blank, Linux kernel will bypass TPM code if there isn't TPM chipset, uroot print "Cannot open TPM: TPM device not available",  not sure it  bypass TPM measure or not. 


1970/01/01 00:03:53 Skip /mnt/nvme0n1p2/lost+found: not significant
1970/01/01 00:03:53 Found 5 boot configs
1970/01/01 00:03:53 {Name:'Ubuntu'  Kernel:/mnt/nvme0n1p2/vmlinuz-5.4.0-88-generic Initramfs:/mnt/nvme0n1p2/initrd.img-5.4.0-88-generic KernelArgs:root=/dev/mapper/ubuntu--vg-ubuntu--lv ro DeviceTree: Multiboot: MultibootArgs: Modules:[]}
1970/01/01 00:03:53 {Name:'Ubuntu, with Linux 5.4.0-88-generic'  Kernel:/mnt/nvme0n1p2/vmlinuz-5.4.0-88-generic Initramfs:/mnt/nvme0n1p2/initrd.img-5.4.0-88-generic KernelArgs:root=/dev/mapper/ubuntu--vg-ubuntu--lv ro DeviceTree: Multiboot: MultibootArgs: Modules:[]}
1970/01/01 00:03:53 {Name:'Ubuntu, with Linux 5.4.0-88-generic (recovery mode)'  Kernel:/mnt/nvme0n1p2/vmlinuz-5.4.0-88-generic Initramfs:/mnt/nvme0n1p2/initrd.img-5.4.0-88-generic KernelArgs:root=/dev/mapper/ubuntu--vg-ubuntu--lv ro recovery nomodeset DeviceTree: Multiboot: MultibootArgs: Modules:[]}
1970/01/01 00:03:53 {Name:'Ubuntu, with Linux 5.4.0-86-generic'  Kernel:/mnt/nvme0n1p2/vmlinuz-5.4.0-86-generic Initramfs:/mnt/nvme0n1p2/initrd.img-5.4.0-86-generic KernelArgs:root=/dev/mapper/ubuntu--vg-ubuntu--lv ro DeviceTree: Multiboot: MultibootArgs: Modules:[]}
1970/01/01 00:03:53 {Name:'Ubuntu, with Linux 5.4.0-86-generic (recovery mode)'  Kernel:/mnt/nvme0n1p2/vmlinuz-5.4.0-86-generic Initramfs:/mnt/nvme0n1p2/initrd.img-5.4.0-86-generic KernelArgs:root=/dev/mapper/ubuntu--vg-ubuntu--lv ro recovery nomodeset DeviceTree: Multiboot: MultibootArgs: Modules:[]}
1970/01/01 00:03:53   0: 'Ubuntu'
1970/01/01 00:03:53   1: 'Ubuntu, with Linux 5.4.0-88-generic'
1970/01/01 00:03:53   2: 'Ubuntu, with Linux 5.4.0-88-generic (recovery mode)'
1970/01/01 00:03:53   3: 'Ubuntu, with Linux 5.4.0-86-generic'
1970/01/01 00:03:53   4: 'Ubuntu, with Linux 5.4.0-86-generic (recovery mode)'
1970/01/01 00:03:53 Trying boot configuration {Name:'Ubuntu'  Kernel:/mnt/nvme0n1p2/vmlinuz-5.4.0-88-generic Initramfs:/mnt/nvme0n1p2/initrd.img-5.4.0-88-generic KernelArgs:root=/dev/mapper/ubuntu--vg-ubuntu--lv ro DeviceTree: Multiboot: MultibootArgs: Modules:[]}
1970/01/01 00:03:53 Cannot open TPM: TPM device not available
1970/01/01 00:03:54 Failed to boot kernel /mnt/nvme0n1p2/vmlinuz-5.4.0-88-generic: kexec.FileLoad() failed: sys_kexec(8, 9, root=/dev/mapper/ubuntu--vg-ubuntu--lv ro, 0) = invalid argument
1970/01/01 00:03:54 Trying boot configuration {Name:'Ubuntu, with Linux 5.4.0-88-generic'  Kernel:/mnt/nvme0n1p2/vmlinuz-5.4.0-88-generic Initramfs:/mnt/nvme0n1p2/initrd.img-5.4.0-88-generic KernelArgs:root=/dev/mapper/ubuntu--vg-ubuntu--lv ro DeviceTree: Multiboot: MultibootArgs: Modules:[]}
1970/01/01 00:03:54 Cannot open TPM: TPM device not available
1970/01/01 00:03:54 Failed to boot kernel /mnt/nvme0n1p2/vmlinuz-5.4.0-88-generic: kexec.FileLoad() failed: sys_kexec(8, 9, root=/dev/mapper/ubuntu--vg-ubuntu--lv ro, 0) = invalid argument
1970/01/01 00:03:54 Trying boot configuration {Name:'Ubuntu, with Linux 5.4.0-88-generic (recovery mode)'  Kernel:/mnt/nvme0n1p2/vmlinuz-5.4.0-88-generic Initramfs:/mnt/nvme0n1p2/initrd.img-5.4.0-88-generic KernelArgs:root=/dev/mapper/ubuntu--vg-ubuntu--lv ro recovery nomodeset DeviceTree: Multiboot: MultibootArgs: Modules:[]}
1970/01/01 00:03:54 Cannot open TPM: TPM device not available
1970/01/01 00:03:54 Failed to boot kernel /mnt/nvme0n1p2/vmlinuz-5.4.0-88-generic: kexec.FileLoad() failed: sys_kexec(8, 9, root=/dev/mapper/ubuntu--vg-ubuntu--lv ro recovery nomodeset, 0) = invalid argument
1970/01/01 00:03:54 Trying boot configuration {Name:'Ubuntu, with Linux 5.4.0-86-generic'  Kernel:/mnt/nvme0n1p2/vmlinuz-5.4.0-86-generic Initramfs:/mnt/nvme0n1p2/initrd.img-5.4.0-86-generic KernelArgs:root=/dev/mapper/ubuntu--vg-ubuntu--lv ro DeviceTree: Multiboot: MultibootArgs: Modules:[]}
1970/01/01 00:03:54 Cannot open TPM: TPM device not available
1970/01/01 00:03:54 Failed to boot kernel /mnt/nvme0n1p2/vmlinuz-5.4.0-86-generic: kexec.FileLoad() failed: sys_kexec(8, 9, root=/dev/mapper/ubuntu--vg-ubuntu--lv ro, 0) = invalid argument
1970/01/01 00:03:54 Trying boot configuration {Name:'Ubuntu, with Linux 5.4.0-86-generic (recovery mode)'  Kernel:/mnt/nvme0n1p2/vmlinuz-5.4.0-86-generic Initramfs:/mnt/nvme0n1p2/initrd.img-5.4.0-86-generic KernelArgs:root=/dev/mapper/ubuntu--vg-ubuntu--lv ro recovery nomodeset DeviceTree: Multiboot: MultibootArgs: Modules:[]}
1970/01/01 00:03:54 Cannot open TPM: TPM device not available
1970/01/01 00:03:54 Failed to boot kernel /mnt/nvme0n1p2/vmlinuz-5.4.0-86-generic: kexec.FileLoad() failed: sys_kexec(8, 9, root=/dev/mapper/ubuntu--vg-ubuntu--lv ro recovery nomodeset, 0) = invalid argument
1970/01/01 00:03:54 No boot configuration succeeded
Exception: localboot exited with 1
[tty], line 1: localboot -grub -d
~/# cd /mnt/
~/mnt# ls
nvme0n1p1
nvme0n1p2
~/mnt# cd nvme0n1p1/
~/mnt/nvme0n1p1# ls
~/mnt/nvme0n1p1# cd ..
~/mnt# cd nvme0n1p2/
~/mnt/nvme0n1p2# ls
~/mnt/nvme0n1p2#
~/mnt/nvme0n1p2#
~/mnt/nvme0n1p2#
~/mnt/nvme0n1p2# ls
~/mnt/nvme0n1p2#

**Comment by johnnylinwiwynn** [comment]
> @johnnylinwiwynn thanks a lot for your comments, the CentOS is workable if I disable BLSCFG from grub. 

The latest boot command have had a little improvement for BLSCFG support, should be able to boot CentOS with BLSCFG enabled.
