### ISSUE TITLE
u-root busybox mode is not working with some go modules

### ISSUE THREAD

**Issue by limbo127** [u-root/u-root#2149]
Hello, 
Impossible to use some external module in bb mode, 
example : 
https://github.com/hanwen/go-fuse/

=> 
 could not import github.com/hanwen/go-fuse/v2/fs (cannot find package "github.com/hanwen/go-fuse/v2/fs" in any of:
        /usr/lib/go/src/github.com/hanwen/go-fuse/v2/fs (from $GOROOT)
        /tmp/workdir/GOLANG/src/github.com/hanwen/go-fuse/v2/fs (from $GOPATH))))

perhaps because 
https://github.com/hanwen/go-fuse/blob/master/go.mod    
that name /v2  and not the root of the github .

Regards, 
Nicolas

**Comment by rminnich** [comment]
hi, can you show me the full command you ran. 

I am not sure how to repro.

**Comment by limbo127** [comment]
hello,
trying with prometheus for example :
makebb -o /tmp/test /tmp/prometheus/

using this patch https://github.com/u-root/gobusybox/pull/53/files
<https://www.google.com/url?q=https://github.com/u-root/gobusybox/pull/53/files&sa=D&source=hangouts&ust=1654773686323000&usg=AOvVaw2meBkNOPL39VIbQps7MAhJ>
 , it's working fine.

Le mer. 8 juin 2022 à 11:12, ron minnich ***@***.***> a
écrit :
