### ISSUE TITLE
pkg/curl doesn't support https

### ISSUE THREAD

**Issue by marcjones-syspro** [u-root/u-root#2151]
**Is your feature request related to a problem? Please describe.**
pkg/curl doesn't support https. If it did, wget and pxeboot would get https support. 

~/# wget https://www.google.com
wget: 2021/10/21 21:52:52 Failed to download https://www.google.com: encountered error Get "https://www.google.com": x509: certificate signed by unknown authority with "https://www.google.com"
Exception: wget exited with 1

cmd/fbnetboot has some https support, but I don't know how complete or portable it is.

**Comment by rminnich** [comment]
it does support https
```
./wget https://www.google.com
```

but that's not the issue
```
/usr/bin/strace -f -o out -v ./wget https://www.google.com
2450479 openat(AT_FDCWD, "/etc/ssl/certs/ca-certificates.crt", O_RDONLY|O_CLOEXEC) = 7
2450479 openat(AT_FDCWD, "/etc/ssl/certs", O_RDONLY|O_CLOEXEC) = 7
grep certs out | wc
    392    2616   42751
```
if you want https, for your u-root command, add this
```
-files /etc/ssl/certs,
```
e.g.
```
u-root -files /etc/ssl/certs
```

and you're good to go.

**Comment by marcjones-syspro** [comment]
Thanks Ron. I'll give this a try. I guess I didn't see https as a curl scheme and got hung up there. From my understanding, the reason we have fbnetboot is because pxeboot didn't support https, so maybe it is something that is easily added.

**Comment by hugelgupf** [comment]
It ain't that easy, but also it is:

wget manually adds https as one of the schemes using the default http
client, and then everything works the way Ron describes.

https://github.com/u-root/u-root/blob/73262e9af9d77fee45e32cd23440d4c6b5cbff95/cmds/core/wget/wget.go#L75

My rec would be, however, to add an explicit flag to pxeboot to pass in a
cert, which we can pass in to a custom http client we can pass in as the
https scheme. That way, it's not just whatever custom implicit thing you
specify somewhere in the OS, but what you specified as a flag to pxeboot.
WDYT?

**Comment by tlaurion** [comment]
@rminnich @hugelgupf so /etc/ssl needs to be packed  through u-root -files statement when building on the host to integrate host's certs?

**Comment by tlaurion** [comment]
> @rminnich @hugelgupf so /etc/ssl needs to be packed through u-root -files statement when building on the host to integrate host's certs?

Opened https://github.com/u-root/u-root/issues/2668 on that matter.
