### ISSUE TITLE
Fix TestDeadProcess in pkg/lockfile/lockfile_test.go

### ISSUE THREAD

**Issue by rminnich** [u-root/u-root#2175]
86757f376561db47a5d242b9dc70b5a88147af86 turns TestDeadProcess off, as it failed in circleci for no clear reason. Needs to get turned back on.

**Comment by rminnich** [comment]
Befire it gets turned back on, we need to know why it failed and how to fix it. Just turning it back on is not the right thing to do.

**Comment by hugelgupf** [comment]
lockfiles are gone
