### ISSUE TITLE
CI: amd64 integration image lacking /etc/group file

### ISSUE THREAD

**Issue by ChriMarMe** [u-root/u-root#2257]
**Describe the bug**
AMD64 integration image missing /etc/group file. 

**To Reproduce**
Write a function which tries to open /etc/group file.

**Expected behavior**
File existence

**Additional context**
Code which requires package std os/user can't rely on proper integration tests if the matching of group id to group name does not work properly.

**Comment by rjoleary** [comment]
I think you would need to create a temporary group file with some fake data and add the file to the following struct: https://github.com/9elements/u-root/blob/main/integration/gotests/gotest_test.go#L95

See how it was done in webboot: https://github.com/u-root/webboot/blob/main/integration/basic_test.go#L56

**Comment by ChriMarMe** [comment]
Would this create side effects of the other integration tests?

**Comment by ChriMarMe** [comment]
Ok, fix worked. Will push that soon
