### ISSUE TITLE
CI/Race job: cmds/core/dd/test_dd.go is flakey

### ISSUE THREAD

**Issue by ChriMarMe** [u-root/u-root#2282]
**Describe the bug**
The CircleCI race job fails at cmds/core/dd/dd_test.go: "512 MiB zeroed file in 1024 1KiB blocks" randomly. 

Error message:
```
--- FAIL: TestDd (66.70s)
    --- FAIL: TestDd/512_MiB_zeroed_file_in_1024_1KiB_blocks (62.59s)
        dd_test.go:527: Test compare function returned: Found 512610304 count of 0x0 bytes, wanted to find 536870912 count
        dd_test.go:530: Test [bs=524288 count=1024 if=/dev/zero] exited with error: signal: killed

```
**To Reproduce**
For me the bug occurs in 2 out of 3 PRs, need to trigger the CI multiple times to make it go away.

**Expected behavior**
The test isn't flakey.

**Comment by walterchris** [comment]
I upgraded the machine to `large` and it seems more reliable.

**Comment by ChriMarMe** [comment]
Looks like that solved the issue.
