### ISSUE TITLE
Change directory in u-root may cause kernel panic

### ISSUE THREAD

**Issue by timchuquanta** [u-root/u-root#2286]
**Describe the bug**
After changing directory in u-root, kernel panic may happen.

Error logs:
> /# cd dev
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x85add8]
> goroutine 103 [running]:
github.com/u-root/u-root/vendor/src.elv.sh/pkg/edit.initLocation.func2({0xc000034143, 0x3})
/data/timchu/SPR/test2/osf/projects/s9s/build/s9s/initramfs/gopath/src/github.com/u-root/u-root/vendor/src.elv.sh/pkg/edit/listing.go:130 +0x58
github.com/u-root/u-root/vendor/src.elv.sh/pkg/eval.(*Evaler).Chdir(0xc000559518, {0xc000034143, 0x3})
/data/timchu/SPR/test2/osf/projects/s9s/build/s9s/initramfs/gopath/src/github.com/u-root/u-root/vendor/src.elv.sh/pkg/eval/eval.go:374 +0xd0
github.com/u-root/u-root/vendor/src.elv.sh/pkg/eval.cd(0x2, {0xc00043e8f0, 0x1, 0x1})
/data/timchu/SPR/test2/osf/projects/s9s/build/s9s/initramfs/gopath/src/github.com/u-root/u-root/vendor/src.elv.sh/pkg/eval/builtin_fn_fs.go:73 +0xbe
reflect.Value.call({0xa452a0, 0xc21d48, 0x2}, {0xb351e7, 0xc00043e8e0}, {0xc0003a9c50, 0x2, 0xc000306b78})
/data/timchu/SPR/test2/osf/projects/s9s/build/s9s/initramfs/go/src/reflect/value.go:556 +0x791
reflect.Value.Call({0xa452a0, 0xc21d48, 0xa1b6e0}, {0xc0003a9c50, 0x2, 0x2})
/data/timchu/SPR/test2/osf/projects/s9s/build/s9s/initramfs/go/src/reflect/value.go:339 +0x9d
github.com/u-root/u-root/vendor/src.elv.sh/pkg/eval.(*goFn).Call(0xc00038f880, 0xc00053a540, {0xc00043e8c0, 0x1, 0x7}, 0xc0003a9c20)
/data/timchu/SPR/test2/osf/projects/s9s/build/s9s/initramfs/gopath/src/github.com/u-root/u-root/vendor/src.elv.sh/pkg/eval/go_fn.go:227 +0x87c
github.com/u-root/u-root/vendor/src.elv.sh/pkg/eval.(*formOp).exec(0xc00054c0b0, 0xc00053a540)
/data/timchu/SPR/test2/osf/projects/s9s/build/s9s/initramfs/gopath/src/github.com/u-root/u-root/vendor/src.elv.sh/pkg/eval/compile_effect.go:377 +0x45b
github.com/u-root/u-root/vendor/src.elv.sh/pkg/eval.(*pipelineOp).exec.func1()
/data/timchu/SPR/test2/osf/projects/s9s/build/s9s/initramfs/gopath/src/github.com/u-root/u-root/vendor/src.elv.sh/pkg/eval/compile_effect.go:122 +0x56
created by github.com/u-root/u-root/vendor/src.elv.sh/pkg/eval.(*pipelineOp).exec
/data/timchu/SPR/test2/osf/projects/s9s/build/s9s/initramfs/gopath/src/github.com/u-root/u-root/vendor/src.elv.sh/pkg/eval/compile_effect.go:121 +0x6be

> /# cd dev
panic: runtime error: iu-root init [optional]: warning creating dir "/sys/fs/cgroup/hugetlb" (mode 0555): mkdir /sys/fs/cgroup: operation not permitted
Kernel panic - not syncing: Attempted to kill init! exitcode=0x00000000
CPU: 1 PID: 1219 Comm: init Not tainted 5.10.50 #1
Hardware name: 
Call Trace:
? dump_stack+0x57/0x6a
? panic+0xf9/0x2ba
? do_exit+0x1ab/0x8b5
? do_group_exit+0x8e/0x8e
? get_signal+0x1a3/0x565
? hrtimer_try_to_cancel+0x22/0xa8
? arch_do_signal+0x31/0x4fc
? __x64_sys_futex+0x132/0x157
? exit_to_user_mode_prepare+0x3f/0xb2
? syscall_exit_to_user_mode+0x8d/0xa1
? entry_SYSCALL_64_after_hwframe+0x44/0xa9
nvalid memory adKernel Offset: 0x39600000 from 0xffffffff81000000 (relocation range: 0xffffffff80000000-0xffffffffbfffffff)
---[ end Kernel panic - not syncing: Attempted to kill init! exitcode=0x00000000 ]---

**To Reproduce**
In u-root, execute "cd" to other folder.

**Expected behavior**
Change to other directory without errors.

**Comment by MDr164** [comment]
Fixed by https://github.com/u-root/u-root/pull/2262
