### ISSUE TITLE
bad strings.TrimRight usage

### ISSUE THREAD

**Issue by sjwheel** [u-root/u-root#2402]
**Describe the bug**

These three files use `strings.TrimRight` when they should use `strings.TrimSuffix`
pkg/boot/bls/bls_test.go
golang/uroot/pkg/boot/grub/config_test.go
pkg/boot/syslinux/config_test.go

**Comment by sjwheel** [comment]
#2403

**Comment by rminnich** [comment]
fixed by #2416
