### ISSUE TITLE
Update the CI

### ISSUE THREAD

**Issue by MDr164** [u-root/u-root#2418]
The CI as some issues like a very flakey arm32 integration test, slow execution time and it's generally missing a few features like stricter linting, actually projecting running in a generic environment (often times things pass locally and fail in the CI or even the other way around!). At the same time: GitHub Actions matured a lot and can be used in the place of CircleCI and CirrusCI. I'd like to tackle that myself, just let me know what you think about moving everything to GitHub Actions.

**Comment by rminnich** [comment]
YES. we moved to github actions on oreboot and it was a gigantic improvement.

**Comment by depate** [comment]
+1 for github actions. 

To keep maybe a certain degree of flexibility there is a tool that was able to generate several CI/CD configurations for different providers from a single source configuration file. I forgot how it's called. Maybe it's over engineered.

**Comment by MDr164** [comment]
I'll put Dagger on my list of things to look into. For now a regular GH Action workflow set might do.

**Comment by 10000TB** [comment]
+1  -- The problem statement is very true

**Comment by patmaddox** [comment]
> GitHub Actions matured a lot and can be used in the place of CircleCI and CirrusCI

GitHub actions doesn't officially support FreeBSD as far as I know. [The method I'm aware of](https://github.com/marketplace/actions/freebsd-vm) requires you to run a FreeBSD VM inside of a MacOS instance. That's pretty janky.

Cirrus CI runs directly on FreeBSD machines, so it should probably be re-instated for FreeBSD verification.

**Comment by MDr164** [comment]
Previously we had Cirrus CI supprot but the Pipeline only ever tested a go build of the main u-root binary which was not worth yet another CI. Our goal would have been to reduce the amount of different CI backends we're running hence my PR for GitHub actions. Yes GitHub does not over native FreeBSD runners and the reason we need macOS as a runner is because it's the only runner supporting nested KVM aka running VMs without significant slowdowns. Now my question is: What makes a FreeBSD VM worth less than a FreeBSD runner on Cirrus? And is it worth adding the overhead of yet another CI back into the mix?

**Comment by MDr164** [comment]
Mostly done by #2781 shall we close this issue or keep it open for the remaining pipelines for e.g. tinygo/tamago?
