### ISSUE TITLE
test-integration-arm flaky

### ISSUE THREAD

**Issue by hugelgupf** [u-root/u-root#2427]
test-integration-arm has been flaky lately. People have been blaming that on timeouts, but if you look at the actual tests, that's not the case.

```
    integration.go:145: 2022/06/15 18:22:26 serial: Kernel panic - not syncing: Attempted to kill init! exitcode=0x0000000b~
```

(from https://app.circleci.com/pipelines/github/u-root/u-root/4185/workflows/3380eb80-9736-4a9e-9eb1-bba0ddb91673/jobs/75711)

exit status 0xb is a signal, signal 0xb (= 11) is SIGSEGV.

@rjoleary recommends moving to qemu 7.

cc @MDr164 @10000TB

**Comment by 10000TB** [comment]
Making an attempt to upgrade arm image to 7.0.0 and see if that helps

**Comment by 10000TB** [comment]
much stable now.  18/19 most recent runs passed https://app.circleci.com/pipelines/github/u-root/u-root?filter=all

**Comment by 10000TB** [comment]
Close this for now, as from my runs in the past few days it is no longer flaky as reported.
