### ISSUE TITLE
Does localboot use kexec?

### ISSUE THREAD

**Issue by hanxinwu1** [u-root/u-root#2506]
Hello, does the localboot or boot command use kexec to boot the Linux operating system? Can the localboot command start the Windows operating system? （linuxboot）Thanks！

**Comment by walterchris** [comment]
Hi,

localboot and boot both use kexec to boot the Linux operating system.

Windows can only booted with UEFI Runtime Services - thus it is not straight forward possible u-root. However there exists a `uefiboot` cmd now that jumps into EDK2's UefiPayload and can boot Windows from there.

I close this - just answered for completeness :)
