### ISSUE TITLE
U-boot guides for Qemu or NoVM? I"m have been working on a programmatic kernel system builder amd image builder

### ISSUE THREAD

**Issue by lostinblue** [u-root/u-root#253]
The search term is quite generic looking for guides on this, I found your blog, but I was hoping you could either provide an up to date guide to build this and use the resulting build with qemu/kvm or novm. Seems most of the work is geared towards containers. I really love the idea of this, it has a lot of uses, and I had already drawn up plans to build something almost identical to this, though I did not think of using the compiler with the interpreter in the way you did, thats very clever.

**Comment by rminnich** [comment]
actually using with qemu/kvm is very simple. 
go run scripts/ramfs.go
qemu -kernel your-kernel -initrd /tmp/initramfs.linux_amd64.cpio

that's it. Please let me know if we can help.
