### ISSUE TITLE
The `dt` package cannot be used on GOOS != linux.

### ISSUE THREAD

**Issue by abarisani** [u-root/u-root#2559]
The naming of [fdt_linux.go](https://github.com/u-root/u-root/blob/main/pkg/dt/fdt_linux.go) currently prevent us from upgrading the u-root package in our [bare metal bootloader](https://github.com/usbarmory/armory-boot/blob/master/exec/linux.go).

This happens because naming the file with the `_linux` suffix tells Go to only load the file with GOOS=linux while we use GOOS=tamago.

I think this is a bug as there is no reason why the `dt` package should be forced only on `GOOS=linux`.

Would you mind renaming the file so that we can upgrade your package?

Thanks!

**Comment by hugelgupf** [comment]
Hm I mean in the meantime you can call New(WithReaderAt(dtb), WithFileName(...)) I suppose. The package is usable on non-linux, only that file wouldn't be compiled there. It's called fdt_linux I suspect because it refers to `/sys/firmware/fdt` which does seem pretty Linux-specific.
