### ISSUE TITLE
binary in the root directory?

### ISSUE THREAD

**Issue by mvdan** [u-root/u-root#2577]
I imagine the ~3.7MiB binary at https://github.com/u-root/u-root/blob/main/gosh was a mistake :) Perhaps too late to rewrite the history at this point. cc @ChriMarMe @rminnich

**Comment by hugelgupf** [comment]
Yes... yeesh

**Comment by hugelgupf** [comment]
I rewrote history. Sorry y'all. Nothing had been tagged yet, not too many commits.
