### ISSUE TITLE
u-root lies about saving tmp dir

### ISSUE THREAD

**Issue by rminnich** [u-root/u-root#2814]
**Describe the bug**
u-root says it is preserving the generated source directory, but it is not

./u-root -gen-dir  ~/tmp/whatever -tags tinygo cmds/exp/rush

13:21:46 Build error: error building: preserving bb generated source directory at /var/folders/vp/n2xq_79s3s549qb4tt4380v00000gp/T/u-root2050172721/builder265485357 due to error:
finding packages failed: could not load packages from file system: failed to add package github.com/u-root/u-root/cmds/exp/rush for errors: 1 error occurred:
	* /Users/rminnich/go/src/github.com/u-root/u-root/cmds/exp/rush/rush.go:95:9: undefined: runone

ronsexcllentmbp:u-root rminnich$ ls /var/folders/vp/n2xq_79s3s549qb4tt4380v00000gp/T/u-root*

ls: /var/folders/vp/n2xq_79s3s549qb4tt4380v00000gp/T/u-root*: No such file or directory

**To Reproduce**
./u-root -gen-dir  ~/tmp/whatever -tags tinygo cmds/exp/rush

**Expected behavior**
I expect it to do what it says it is doing.
13:21:46 Build error: error building: preserving bb generated source directory at /var/folders/vp/n2xq_79s3s549qb4tt4380v00000gp/T/u-root2050172721/builder265485357 due to error:

**Additional context**
It worked as of last february, and is broken again.

**Comment by hugelgupf** [comment]
Among other things, https://github.com/u-root/mkuimage is fixing this (tho this one is easy).
