### ISSUE TITLE
localboot can't find partition (and thus can't boot)

### ISSUE THREAD

**Issue by Buanderie** [u-root/u-root#2911]
**Describe the bug**
I made a minimal bootable disk with u-root and grub2 (with a generic kernel)
The disk is made of a single EFI/vfat bootable partition with u-root, grub and the kernel binary
I'm trying to test localboot to load another kernel from another disk.

**To Reproduce**
```
2024/02/08 19:00:26 Device: BlockDevice(name=sda1, fs_uuid=39b3-5c73)
2024/02/08 19:00:26 Device: BlockDevice(name=sr0, fs_uuid=)
2024/02/08 19:00:26 Looking for partition with GUID 39b3-5c73
2024/02/08 19:00:26 no partitions with GUID 39b3-5c73
Exception: localboot exited with 1
[tty 101], line 1: localboot -kernel vmlinuz -guid 39b3-5c73 -d
/#                                                                   root@(none)
```

As you can see, my disk is listed and GUID matches.

**Expected behavior**
Not sure, since I don't know what I should expect if localboot was working :)

I'm sure I'm doing something wrong here

**Comment by hugelgupf** [comment]
I recommend the use of `cmds/boot/boot` for local/GRUB boots instead. We should probably move `localboot` to `exp` to mark it deprecated.
