### ISSUE TITLE
rm -r flag does not work 

### ISSUE THREAD

**Issue by ananion-cation** [u-root/u-root#307]
I wanted to remove multiple files 

I ran rm -r to remove all files in a directory and got the following error: flag provided but not defined: -r
Usage: rm [-Rrvi] file...:
wait:exit status 2
NOTE: this is going to fail right now

**Comment by rminnich** [comment]
This needs more information.

**Comment by rminnich** [comment]
Was this in busybox mode? if you 
cd cmds/rm
go build 
and run rm -r with that version, does it work?

Is the r switch in rm.go?

**Comment by ananion-cation** [comment]
yes, this was in busybox mode. It works when I build it locally. I am editing the files now based on ls (which works in bb mode)

**Comment by rjoleary** [comment]
For me, `-r` works in both busybox mode and as a single binary. Since the issue was filed, there have been changes to bb which might have fixed it.
