### ISSUE TITLE
u-root.tk now points to a domain squatter page

### ISSUE THREAD

**Issue by chingcodes** [u-root/u-root#392]
The project url is a dead url ( that shows ads). Did the DNS get renewed?

### Todo
- [ ] buy a new domain and config the dns servers
- [ ] regenerate the static website with a new domain and merge it on master

**Comment by ryukinix** [comment]
Sorry for that, I'm the owner of the domain. But I just lost the domain because I forgot to renew and the freenom guys are smart, if you forgot to renew you need to pay the next year. We need a new domain since now is not more free or pay on freenom for the last year. @rminnich is your turn.

![image](https://user-images.githubusercontent.com/7642878/31825699-6adf9818-b589-11e7-9849-f9968450525e.png)

**Comment by ryukinix** [comment]
But if we will pay, would be better another domain, like `uroot.org` or `u-root.org`.

**Comment by hugelgupf** [comment]
I just went ahead and registered u-root.com.

**Comment by ryukinix** [comment]
Yes... too late. But do you not think that `u-root.org` is good enough?

**Comment by hugelgupf** [comment]
I'd have preferred .org, but it was taken. Unless you took it?

**Comment by ryukinix** [comment]
No, I don't took it. Sorry, I misunderstood the dns seller site that I was looking for alternatives. The `u-root.org` was indeed taken. `.net` is available, although.

**Comment by rjoleary** [comment]
I forget the exact steps, but there are a few things needed to rebuild the website with a new URL:

1. The site URL needs changing in the yaml: https://github.com/u-root/u-root/blob/master/website/mkdocs.yml
2. Rebuild the site with the mkdocs tool: http://www.mkdocs.org/
3. This should recreate the /docs folder. Make sure the /docs/CNAME file contains the new URL.
4. Merge this change into master.
5. IIRC github.io will pickup the change and redeploy the site automatically. However, some additional steps might be needed to reconfigure github.io and the DNS servers.

**Comment by ryukinix** [comment]
Yes, this was exactly what I did in the first version @rjoleary.

**Comment by ryukinix** [comment]
Since someone buy a new domain, we can generate the static website.

**Comment by rminnich** [comment]
I bought u-root.tk back. There are way too many talks out there with that name. We have it for 5 years. 
You need to tell me how to set it up.

**Comment by rminnich** [comment]
So the plan is we just let u-root.tk die in a few years, we don't reference it any more, but we don't want to let it break. We can't just instantly turn it off, there are too many presentations out there that use it. 
So how do I configure it?

**Comment by rminnich** [comment]
why am I not able to reach this page from github.io? What's the URL? I'm ready to do the CNAME dance but ...

**Comment by rminnich** [comment]
OK folks it's back. Thanks chingcodes for pointing this out, and thanks to all of you for the discussion. This gives us time to transition with a bit less excitement.
