### ISSUE TITLE
Update to Linux kernel with memconsole_coreboot support and enable it

### ISSUE THREAD

**Issue by paulmenzel** [u-root/u-root#397]
Support to export CBMEM console to `/sys/firmware/log` was added in Linux 4.12. Would it make sense to update to that version and enable that configuration?

I only found `scripts/config-3.14.17` in the repository.

**Comment by bluecmd** [comment]
Thanks for the suggestion! I had a look and that file has been removed, and I think while we have some opinions on what to enable in your kernel, we're not in the kernel building business.
