### ISSUE TITLE
bb/dhclient broken together

### ISSUE THREAD

**Issue by hugelgupf** [u-root/u-root#425]
Not sure why yet. Not sure if it's my ramfs refactor or if dhclient is broken or if our winterfell setup is broken. Suspecting either of the first two.

**Comment by rminnich** [comment]
I know that dhclient still works on NiChrome, if that helps.

**Comment by rminnich** [comment]
Also some kind of info about what happened would be nice to have.

**Comment by hugelgupf** [comment]
False alarm I guess. This was just the random number issue.
