### ISSUE TITLE
dhclient: rand issues / routes not added until random initialized

### ISSUE THREAD

**Issue by hugelgupf** [u-root/u-root#427]
winterfell booting:

% dhclient &

works immediately with math/rand instead of crypto/rand, and gets me an IP. A couple seconds later, after I type enough stuff:

% ip route
ip: Iface       Destination     Gateway         Flags   RefCnt  Use     Metric  Mask            MTU     Window  IRTT                                                       
random: fast init done
random: fast init done
error: error: reply does not contain IAAddr
% ip route
    
ip: Iface       Destination     Gateway         Flags   RefCnt  Use     Metric  Mask            MTU     Window  IRTT                                                       
eth0    00000000        FEDD6064        0003    0       0       0       00000000        0       0       0                                                                               
eth0    80DD6064        00000000        0001    0       0       0       80FFFFFF        0       0       0            

So random is initialized, as seen by the printk output there, and *then* dhclient gets an error and the correct routes appear.

Filing this to look into later.

**Comment by rminnich** [comment]
Are you sure there's not some other usage of rand going on somewhere else? I'm suspicious that we get no output until after random is up. 

An strace would be useful here.

bb -add /usr/bin/strace
