### ISSUE TITLE
u-root should Glob

### ISSUE THREAD

**Issue by rminnich** [u-root/u-root#440]
The problem with u-root counting on the shell globbing is that programs, like the usb command in NiChrome, are now required to run an intermediate shell to get the globbing done, or do the globbing themselves, ... it's all kind of annoying. I don't personally view this change as an improvement. I can deal with it, I just don't much like it. 

How does a Go program in, e.g., NiChrome, invoke the u-root command? Please don't tell me to run an intermediate shell. We've avoided dependence on a particular shell in u-root for many years and I don't want to reintroduce that sort of thing. The intermediate shell starts to bring in all kinds of problems of its own, such as its search for . files, and lots of other environment, that may not exist in a pared down configuration.

**Comment by rminnich** [comment]
well I can manage, so I'm closing this.

**Comment by hugelgupf** [comment]
Another Go program should invoke u-root by importing the u-root package and calling uroot.Build. I messed up where I put Build, so let me move that real quick :)

**Comment by rminnich** [comment]
OK, I'll wait to see.
