### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by hugelgupf** [u-root/u-root#442]
Hey Ron, how is the website currently hosted? On your Linode?

Maybe we should migrate to github.io pages. No hosting and easy to maintain.

**Comment by rminnich** [comment]
it's hosted on github. uroot.tk just points to it.

**Comment by hugelgupf** [comment]
How can I point u-root.com at it as well?

**Comment by bkochendorfer** [comment]
It's probably best to have `u-root.com` redirect to `uroot.tk`. That way there is one source of knowledge and you can hold down multiple TLDs.

**Comment by rminnich** [comment]
I agree.

**Comment by hugelgupf** [comment]
`u-root.com` redirects to `u-root.tk` now that I've finally set up nginx on that server.

Ron, did you happen to accidentally claim `u-root.com` as a Google Apps domain? I was gonna add it as an alias to my existing account, but Google protested that it already existed elsewhere. I'm happy to verify yours via DNS.
