### ISSUE TITLE
Testing improvements

### ISSUE THREAD

**Issue by hugelgupf** [u-root/u-root#445]
E.g.

 - it should unpack cpio for both build modes, chroot into it, start shell, and try at least one command
 - it should lzma -9 a bb-mode build and check that its size does not exceed 3M (arbitrary limit for now)

**Comment by hugelgupf** [comment]
I'm probably going to take a look at both of those this weekend. Possibly a qemu test.

**Comment by rjoleary** [comment]
@rminnich completed the first bullet point in https://github.com/u-root/u-root/blob/master/scripts/testramfs/testramfs.go

**Comment by rjoleary** [comment]
I opened #888 for the second bullet.
