### ISSUE TITLE
Investigate better compression algorithms

### ISSUE THREAD

**Issue by hugelgupf** [u-root/u-root#497]
We were told today that there are newer and better compression algorithms than lzma that the kernel supports for initramfs. We should look into that, since size is important for us.

**Comment by bensallen** [comment]
Arjan from ClearLinux did some good research into comparing the algorithms: https://clearlinux.org/blogs/linux-os-data-compression-options-comparing-behavior.

For best compression size xz or the new zstd (not added to kernel yet for initrd it appears: http://lists-archives.com/linux-kernel/28937359-add-x86-zstd-kernel-compression.html).

**Comment by hugelgupf** [comment]
We've been using xz at Google for a while, but in general u-root doesn't dictate compression anyway. Closing this issue since this is a beyond u-root issue.
