### ISSUE TITLE
Investigate strange coverage numbers

### ISSUE THREAD

**Issue by hugelgupf** [u-root/u-root#531]
go test -cover does not seem to collect coverage on everything we want. E.g. take

go test -cover ./cmds/wget

which gives 0%, yet there is a test there that covers a bunch of stuff.

Someone should investigate how go test -cover gets its coverage numbers and fix our usage of it or fix go test -cover.

**Comment by hugelgupf** [comment]
I'm gonna guess it has something to do with the `testutil` package.

**Comment by hugelgupf** [comment]
@prattmic you deal with coverage all the time, if you have 5 mins can you take a guess and tell us what's wrong?

**Comment by rjoleary** [comment]
Happy boxing day!

Is this a duplicate of https://github.com/u-root/u-root/issues/116 ?

If it is, our tools are not smart enough to fix it.

**Comment by prattmic** [comment]
This is definitely a dup of #116.
