### ISSUE TITLE
Turn on golint in u-root

### ISSUE THREAD

**Issue by hugelgupf** [u-root/u-root#533]
Whoever takes this on is likely going to have to fix *a lot* of issues in the code base. Documentation alone will likely make up several hundred to thousand lines of changes.

**Comment by hugelgupf** [comment]
It should not be mandatory, by the way, but it should be prominent enough to make you fix some things. E.g. sometimes, ALL_CAPS names are fine in Go (e.g. if you are taking it from the Linux kernel), but golint will complain about that.

```
$ golint ./cmds/... | wc -l
232
$ golint ./pkg/... | wc -l
118
```

(this is not in master, but in my pxeboot branch, so numbers may vary)

**Comment by rjoleary** [comment]
golint has been enabled in circleci for a while.
