### ISSUE TITLE
Which standard do we follow for commands?

### ISSUE THREAD

**Issue by rck** [u-root/u-root#538]
I did not want to hijack https://github.com/u-root/u-root/issues/116, but it is funny that `pwd` was mentioned. I had some fun with it recently before the toggling of `-L` `-P` made any sense to me. Actually, I was close to send a PR removing that part because I thought it is a leftover before `flag` was used. Good I was finally reading the OpenBSD man-page. `man pwd` on GNU/Linux is pretty much useless.

Is there any agreement on what "standard" we are using? POSIX, GNU, a mix? https://github.com/u-root/u-root/blob/master/CONTRIBUTING.md contains: "We want to implement some of the common commands that exist in upstream projects and elsewhere, but we don't need to copy broken behavior.". Hm, who defines broken behavior?

One more example: I have a half-finished implementation of `tr`. It looks like a no-brainer, but has more quirks than you might think, maybe that is why nobody did it so far. The GNU man-page is completely useless to answer details, you need to read the source code. The OpenBSD man page answered all the questions I had so far. What would be the "perfect" `tr`? The BSD/POSIX one? The GNU one? The busybox one?

I understand that this is not a top-priority, but at least to new guys like me it is confusing, or I overlooked it in the documentation. This will not happen overnight, but a goal/mission statement could help. Even a bit more confusing: I had PRs where I got feedback along the lines that this and that has to change because $GNUtool behaves differently. On the other hand our `ls` does not produce the same output as the "normal" `ls` (showing '.' on `-a`), and in that case there was a statement from Ron that this is okay. So yes, it is confusing for new people that want to write code, especially in `cmd/` and don't know what the expected output actually is.

**Comment by rminnich** [comment]
Go ahead and use the BSD reference for your tr, and you can cite the man page in your code as the source of truth. It sounds very good. 

As for your question about broken behavior: this is a hard one. I don't like a lot of what GNU did to the unix commands. I used to define broken behavior as "most of what GNU added to POSIX", but many of us define POSIX as broken too. There are examples out there of what not to do, like cat -v:
http://harmful.cat-v.org/cat-v/

There's lots of people out there who will claim to understand what they think is unix philosophy, but, speaking as someone who was there in the beginning, I'd have to disagree. The system that, today, best fits Unix philosophy is Plan 9, written by the original Unix creators, who probably know Unix philosophy. But nobody uses Plan 9. 

Do you hate the rush shell? Probably. Does the rush shell follow Unix philosophy? Much more so than bash or zsh. Do you use bash or zsh? Probably. 

But just look at the mess of standard kexec: each command has 2, and in one case, 3 switches meaning the same thing. What's wrong with a single switch for a single operation? 

But, that said, I've had to be less curmudgeonly about this lately and accept that no matter what I think, some people find this stuff handy, so I yield the point. Just look at echo -E :-)

Part of the goal of u-root was to create a standard set of tools without what I consider to be GNU ugliness. But ugliness always involves a judgement call: "I know it when I see it." And, let's face it, who among us is always going to get that right? Not me.

I agree with you: this is confusing. I think some of that text could be rewritten. I'd be happy to take changes to improve it. 

Thanks for your contributions!
