### ISSUE TITLE
We need a wireless stack in Go

### ISSUE THREAD

**Issue by rminnich** [u-root/u-root#59]
This is a big job but we really need it.

**Comment by msingle** [comment]
would https://github.com/mdlayher/wifi help?

**Comment by rminnich** [comment]
this looks GREAT. Yes, I think it could help.

**Comment by rjoleary** [comment]
https://github.com/u-root/u-root/tree/master/cmds/wifi

@jbeta51 You've been working with wifi on nichrome recently. If you think it's good, please close this issue.
