### ISSUE TITLE
Yocto integration

### ISSUE THREAD

**Issue by hugelgupf** [u-root/u-root#608]
I believe @subhav has been looking into this possibility.

**Comment by bluecmd** [comment]
u-bmc might be interested in what comes out of this.

**Comment by bluecmd** [comment]
For some reason GitHub unassigned @subhav and I cannot reassign again. Oh well.

**Comment by subhav** [comment]
Ah, I'm no longer working on anything related to u-root/LinuxBoot. This should have been unassigned a while ago. Thanks.

**Comment by rminnich** [comment]
no idea what yocto integration means. Closing.
