### ISSUE TITLE
dd: tests are really slow under race detector.

### ISSUE THREAD

**Issue by hugelgupf** [u-root/u-root#616]
```
ok  	github.com/u-root/u-root/cmds/dd	262.002s
```

from https://circleci.com/gh/u-root/u-root/3245

**Comment by bensallen** [comment]
With #621 dd_test is down to 54.272s in CircleCI. It's the outlier by quite a ways. Next slowest test is pkg/uroot at 14.5s.

**Comment by bensallen** [comment]
The race CircleCI job is down to 01:32, which is within the same range of the other jobs. I think this is likely good enough.
