### ISSUE TITLE
Code-review: how about go back to it?

### ISSUE THREAD

**Issue by ryukinix** [u-root/u-root#63]
Hey @rminnich, what do you think about this one? I think a code review system like gerrit is very nice, but [BarKeep](http://getbarkeep.org/) seems is more pragmatic.

**Comment by rafaelcn** [comment]
The tool seems very intuitive, far simple than gerrit! But as we discussed in bringing this - the project - to Github there's no point in moving back to a code review again I think.

**Comment by ryukinix** [comment]
I think the productivity of group was better with a code review system.

**Comment by ryukinix** [comment]
I think github code review system is pretty good. Maybe we can disable the pullapprove and use just the codereview system of github. @rafaelcn, @rminnich

**Comment by rafaelcn** [comment]
I agree with this as well. Github review system has improved, actually, it now has one.
