### ISSUE TITLE
bb mode: only u-root vendor directory is used

### ISSUE THREAD

**Issue by hugelgupf** [u-root/u-root#649]
Let's say you are building u-root with [Nash](https://github.com/NeowayLabs/nash), or github.com/hugelgupf/foo.

Now, foo includes a dependency on github.com/hugelgupf/bar, which is vendored in foo, but not in u-root.

When you build u-root in bb mode with foo, only vendored dependencies in u-root are used; the foo ones are ignored. You also get an import error if you don't happen to have bar in your GOPATH.

There are two issues here: 
 * Dependency in external repo that u-root doesn't vendor.
 * Conflicting dependencies. E.g. u-root vendors bar @ abcdef, but foo vendors bar @ defghb.

Here's a potential, kind of complicated proposal: 
 * bb mode builds in $TMPDIR/src/bb rather than $GOPATH/src/github.com/u-root/u-root/bbsh
 * bb mode then uses GOPATH=$TMPDIR
 * bb mode builds a synthesized vendor directory in this env, and rewrites all non-standard imports relative to that.
 * conflicting vendored dependencies are vendored twice with different names (bar1, bar2) and included as bar1 and bar2 in the commands that use them.

cc @rjoleary

**Comment by ryukinix** [comment]
Yes, this is really a problem. I tried before embedd nash with u-root and I can confirm, this happens.

**Comment by hugelgupf** [comment]
This was solved at some point.
