### ISSUE TITLE
Add FIT image support to kexec

### ISSUE THREAD

**Issue by hugelgupf** [u-root/u-root#724]
In lieu of actually making kexec work on arm/etc, it should be pretty easy to kexec FIT images. This'd be neat for compatibility with u-boot bootloaders.

Beyond this, we can also actually just make kexec work. But that requires some more time.

**Comment by hugelgupf** [comment]
cc @rjoleary

**Comment by rjoleary** [comment]
This will be easy after the zimage kexec works.

**Comment by rjoleary** [comment]
There is a fitboot command now.
