### ISSUE TITLE
gVisor + u-root distro

### ISSUE THREAD

**Issue by hugelgupf** [u-root/u-root#732]
One of those ideas for Go enthusiasts: an "all Go secure container runtime Linux distro". Include kubelet, docker, gVisor, u-root. Go userspace, Go kernel, and Linux ends up being "just" the hypervisor. Basically a "kubelet distro".

**Comment by rjoleary** [comment]
Maybe it would be something interesting to see in http://www.qemu-advent-calendar.org/2016/ ? It looks like they have a new calendar every two years.

**Comment by pwFoo** [comment]
Any progress with gVisor (runsc / docker) running with u-root? Just shell with gVisor / run(s)c or docker would be nice!

**Comment by hugelgupf** [comment]
I'm going to close this as infeasible for now, since gVisor is only buildable with bazel. (Someone has a hacked up non-bazel version, but it's likely to break.)
