### ISSUE TITLE
Create constants we can use for major and minor numbers

### ISSUE THREAD

**Issue by rminnich** [u-root/u-root#745]
We need constants, probably in pkt/uroot/const.go, for things not well defined, such as major and minor sizes

**Comment by rjoleary** [comment]
It also needs OS-specific encode/decode functions for device nodes.

Right now, support for Linux's large device nodes (values >255) are very broken in u-root. For example:

```
$ mknod testnod b 1024 1024
# Created testnod with (1028, 0)

# When testnod2 is (1024, 1024)
$ ls -l testnod2
brw-r--r-- root root 17408, 0 May 22 22:57 testnod2
```

**Comment by rjoleary** [comment]
I'll work on fixing this and creating the consts package.
