### ISSUE TITLE
Able to choose default shell from cmd line when building

### ISSUE THREAD

**Issue by hugelgupf** [u-root/u-root#748]
let's give users the option.

**Comment by hugelgupf** [comment]
right now, our init tries to exec "sh" and then "rush". https://github.com/u-root/u-root/blob/master/cmds/init/init.go#L37 

you should be able to choose a default shell from the command line. It's harder to actually change the init code dynamically, so let's just settle on running "/bbin/defaultsh" or "/buildbin/defaultsh" in init permanently and adding a symlink dynamically.

i.e.

u-root --default-shell=elvish github.com/u-root/elvish

means the initramfs has the following files in /bbin:
... bb [binary]
... elvish -> bb [symlink]
... defaultsh -> elvish [symlink]

and in init we try to run "defaultsh" first and fall back to "sh" and "rush".

**Comment by hugelgupf** [comment]
talking to subhav, realized that doesn't actually 100% work, as "defaultsh" will be the arg[0] and it won't recognize elvish in bb mode. hm. Maybe that means a special thing to make bb also recognize defaultsh as arg[0] to go to your chosen default shell?

**Comment by rjoleary** [comment]
The code changes might be similar to https://github.com/u-root/u-root/pull/810
