### ISSUE TITLE
Kernel requirements?

### ISSUE THREAD

**Issue by prologic** [u-root/u-root#787]
I noticed booting up an initramfs in source mode that the bootup complained of a bunch of missing cgroup paths in `/sys/...`. What are the kernel requirements? Same as for Docker as documented [here](https://github.com/moby/moby/blob/master/contrib/check-config.sh)?

**Comment by prologic** [comment]
Can we update the README/docs to reflect this if so?

**Comment by hugelgupf** [comment]
We should make those shut up. We automatically try to mount them, but they're not necessary for anything u-root-specific.

**Comment by hugelgupf** [comment]
@rminnich has been working on a separate kernel requirement doc.

**Comment by prologic** [comment]
So if these are **not** are hard requirement; I've had little luck booting into anything useful. What should be the end result here? Drop into a shell? A getty-style login? What? (*I didn't see any of this; just errors*)

**Comment by hugelgupf** [comment]
You should see a shell prompt, %. Is it reproducible in qemu? (Not sure you can share the kernel you're using, though.)

**Comment by prologic** [comment]
It is; Let me spend some time building a branch that repros this.


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by hugelgupf** [comment]
We've documented some of the configs we use in tests here https://github.com/u-root/u-root/tree/master/configs.

We should rewrite that to be the u-root configs, but there's something. (to be improved.)
