### ISSUE TITLE
Enable website: why not?

### ISSUE THREAD

**Issue by ryukinix** [u-root/u-root#82]
We need just this to enable our website and get visible.

`mv website docs`

And activate gh-pages by:

![docs](http://i.imgur.com/mdHyuH4.png)

I think we can create a more friendly documentation on README.md too.

**Comment by rminnich** [comment]
YEAH!
LGTM

**Comment by ryukinix** [comment]
@rminnich, you can create a pull-request for this? I wanna work on docs with some friends. We think really great if the README.md and website has a clear and usefull documentation about the project (how does, why this, what the deal and so on).

**Comment by ryukinix** [comment]
We need setup yet the GitHub Pages as described in the picture of this issue. I can't do that, just you @rminnich. Would be cool a CNAME like u-root.tk? (I can take for free)

**Comment by rminnich** [comment]
What permissions do you need to do this? I will give them to you.

**Comment by ryukinix** [comment]
I need be owner from organization to change that type of things, the settings of repository. You can go to here https://github.com/orgs/u-root/people and change this. After that I can setup this.

**Comment by rminnich** [comment]
Done.
