### ISSUE TITLE
bb: Command flag contamination

### ISSUE THREAD

**Issue by rjoleary** [u-root/u-root#834]
Today, I saw a `-soshtml` flag on the `kexec` command while running in bb mode. The flag should not be there.

**Comment by rjoleary** [comment]
The `-soshtml` isn't an issue with bb; it's actually in a package imported by `init`. We'll need to fix-up the package.

**Comment by rjoleary** [comment]
@hugelgupf Also mentioned he saw a possible contamination with testing flags.

**Comment by hugelgupf** [comment]
Contamination comes from pkg/sos, which always declares the soshtml flag.

Contamination also comes from elvish, which imports "testing" in non-test files. testing always declares all the testing flags.

**Comment by hugelgupf** [comment]
@TrevorFarrelly can you remove the soshtml flag from pkg/sos and put it in the command it belongs to?

**Comment by rjoleary** [comment]
> Contamination comes from pkg/sos, which always declares the soshtml flag.

This is now fixed. Thanks you Jorge and Trevor!

> Contamination also comes from elvish, which imports "testing" in non-test files. testing always declares all the testing flags.

Can we modify our fork of elvish so it doesn't do that?

**Comment by hugelgupf** [comment]
hey @rminnich - we still investing in elvish, or ash?
