### ISSUE TITLE
CreateInitramfs(ExtraFiles: {<>, ""}) pulls in the current directory

### ISSUE THREAD

**Issue by ddiss** [u-root/u-root#857]
I noticed the following unexpected behaviour:
Calling CreateInitramfs() with ExtraFiles set to [/home/ddiss/isms/kernel/linux/mods/lib/modules/4.18.0-rc7+/modules.dep:lib/modules/4.18.0-rc7+/modules.dep ] (note the trailing whitespace) and OutputFile set to a path under the current directory resulted in a cpio image that includes the current working directory with what appears to be an exceedingly large number of (recursive) OutputFile entries (CreateInitramfs() eventually dies with ENOSPC).

This does not occur once the trailing "" slice entry is removed and ExtraFiles is set to [/home/ddiss/isms/kernel/linux/mods/lib/modules/4.18.0-rc7+/modules.dep:lib/modules/4.18.0-rc7+/modules.dep].

I assume somewhere along the way the "" entry is somehow interpreted as "."

**Comment by hugelgupf** [comment]
Ah, I bet filepath.Abs("") resolves to the cwd. I'll have a PR out in a sec.
