### ISSUE TITLE
Fix bgbuild

### ISSUE THREAD

**Issue by rjoleary** [u-root/u-root#881]

**Comment by hugelgupf** [comment]
Can you comment on what this means?

**Comment by rjoleary** [comment]
bgbuild was disabled by default in #514. This issue is to see if we can and whether we should enable it.

**Comment by hugelgupf** [comment]
What is bgbuild?

What is it supposed to do?

What's broken?

**Comment by rjoleary** [comment]
Since source mode is on it's way out, this is no longer necessary.
