### ISSUE TITLE
How to export variables in shell?

### ISSUE THREAD

**Issue by pwFoo** [u-root/u-root#912]
I need to export / set variables in shell / rush.
Is it possible? Something like 
```
export DOCKER_RAMDISK=true
```

**Comment by rjoleary** [comment]
rush's environment variables work something like this:

```
% echo true > /env/DOCKER_RAMDISK
% echo $DOCKER_RAMDISK
true
```

I don't believe they are exported.

**Comment by rjoleary** [comment]
You might get more mileage if you use [gosh](https://github.com/mvdan/sh) or elvish.

**Comment by pwFoo** [comment]
Thanks @rjoleary!

Found that way by tests. I think by output a not set variable in rush? Works fine for me.
