### ISSUE TITLE
rush: pipe output to following command

### ISSUE THREAD

**Issue by pwFoo** [u-root/u-root#930]
Is something like that used in bash possible?
```
echo "123" |  cmd <output_from_echo>
```
```
cmd $(echo "123") # use command result
```

I have a command output and need to pipe it to the next command...

**Comment by hugelgupf** [comment]
Now that we're using elvish, do you still need something like this?

Also, @rminnich, want to make this a feature request for ash?

**Comment by rjoleary** [comment]
If you want good shell features, use elvish.
