### ISSUE TITLE
How about a verbose mode on scripts/ramfs.go?

### ISSUE THREAD

**Issue by ryukinix** [u-root/u-root#94]
# Disclaimer

At least on my machine (386), the ramfs.go now really take a good time to get into a u-root shell, about minutes. The debug mode has a lot of information, but is really annoying use this for anything instead debug. 
# Idea

How about create a `-v` option to put on stdout few information about what u-root are doing on ramfs.go? Is really scary don't know what he's doing on the normal mode. I think we don't need do too much, like a progressbar of compiling. Just print the sections of procedures to get into the ramfs would be good... searching libs,local variables, compiling source, preparing chroot and etc. 

A minimal verbose mode. What you do think, guys?

**Comment by rafaelcn** [comment]
Ron already did that, look at the u-root slack and also into ramfs.go code, it has a -v option and also a ludicrous (or something like that) one.

--
Regards,
Rafael Campos Nunes.
rafaelnunes737@hotmail.com<mailto:rafaelnunes737@hotmail.com>


Le 16 oct. 2016 ? 14:00, "Manoel Machado" <notifications@github.com<mailto:notifications@github.com>> a ?crit :


We, at least my machine, the ramfs.go now really take a good time to get into a u-root shell. The debug mode has a lot of information, but is really useful for debug. How about create a -v option to put on stdout few information about what u-root are doing on ramfs.go? Is really scary don't know what he's doing on the normal mode. I think we don't need do too much, like a progressbar of compiling. Just print the sections of procedures to get into the ramfs would be good... searching libs,local variables, compiling source, preparing chroot and etc. A minimal verbose mode. What you do think, guys?

-

**Comment by rminnich** [comment]
Can you see if -v works for you?
Thanks!

**Comment by ryukinix** [comment]
```
u-root git/master  26s
❯ go run scripts/ramfs.go -test -v
flag provided but not defined: -v
Usage of /tmp/go-build327305449/command-line-arguments/_obj/exe/ramfs:
  -cpio string
    	An initial cpio image to build on
  -d	Debugging
  -removedir
    	remove the directory when done -- cleared if test fails (default true)
  -test
    	test the directory by chrooting to it
  -tmpdir string
    	tmpdir to use instead of ioutil.TempDir
  -useinit
    	If there is an existing init, don't replace it
exit status 2
```

**Comment by rafaelcn** [comment]
Well, that's weird. Did you saw the code inside ramfs?

--
Regards,
Rafael Campos Nunes.
rafaelnunes737@hotmail.com<mailto:rafaelnunes737@hotmail.com>


Le 17 oct. 2016 ? 09:28, "Manoel Machado" <notifications@github.com<mailto:notifications@github.com>> a ?crit :


u-root git/master  26s
? go run scripts/ramfs.go -test -v
flag provided but not defined: -v
Usage of /tmp/go-build327305449/command-line-arguments/_obj/exe/ramfs:
  -cpio string
        An initial cpio image to build on
  -d    Debugging
  -removedir
        remove the directory when done -- cleared if test fails (default true)
  -test
        test the directory by chrooting to it
  -tmpdir string
        tmpdir to use instead of ioutil.TempDir
  -useinit
        If there is an existing init, don't replace it
exit status 2


-

**Comment by ryukinix** [comment]
Not yet, because I just was walking around and checking the executions I propose that issue. Where is the problem?

**Comment by rafaelcn** [comment]
Ok, the `-v` flag should be there as Ron commit #86 shows that.

**Comment by ryukinix** [comment]
That question is: anybody try use that on head of master?
