### ISSUE TITLE
New command curl - Wrong wget doc comment

### ISSUE THREAD

**Issue by JohnAZoidberg** [u-root/u-root#942]
The comments at the top of `cmds/curl/curl.go` say:
```
// Wget reads one file from a url and writes to stdout.
```
and
```
// Example:
//     wget http://google.com/ > e100.html
```
which is not correct. That would be the behaviour of `curl`, a command which is not yet implemented. The `wget` code in this file correctly implements `wget` semantics.

I would fix this comment to describe `wget` correctly and also add the `curl` command.

**Comment by bkochendorfer** [comment]
Closing as this should be resolved by https://github.com/u-root/u-root/pull/963
