### ISSUE TITLE
bb builder fails to create lock files if the hard links crosses file systems

### ISSUE THREAD

**Issue by insomniacslk** [u-root/u-root#954]
The busybox mode uses a library (github.com/nightlyone/lockfile) that creates hardlinks in order to do locking. If the source and destination of the link are on different file systems, this of course fails (hard links cannot span across filesystems), and it's breaking the build for us under those conditions.

It's a strong assumption that a hard link can always be done - what about switching to a locking library that uses a different approach?

**Comment by insomniacslk** [comment]
cc @tfg13 @Natolumin

**Comment by hugelgupf** [comment]
Lolwat. Sorry about that, I thought that locking library did something sane.

**Comment by insomniacslk** [comment]
no worries! As discussed on Slack let's switch to something saner :) or let's ask them to use symlinks on non-windows platforms, either works for us

**Comment by insomniacslk** [comment]
I've opened an issue (and will likely send a PR) to the `lockfile` library. Otherwise I guess we should switch away to another library or write it ourselves
