### ISSUE TITLE
SSH does not support command line arguments correctly

### ISSUE THREAD

**Issue by bluecmd** [u-root/u-root#956]
Right now the shell will use rush if it is installed, which is a pretty poor shell.

For SCP we need something that has -c with good support for arguments as well, which is not the case right now.

We should redo some of this stuff to be better.

**Comment by hugelgupf** [comment]
We just switched the shell to be elvish by default yesterday. Have you pulled?

**Comment by bluecmd** [comment]
Look at that! Nice!

I'll keep this open as I'm pretty sure that sshd does not treat multi-args completely correctly which is the second half of this.

**Comment by bluecmd** [comment]
Turns out I was just missing a thing in SCP and that is what was missing from SSHd.
