### ISSUE TITLE
hwclock: Support setting the hardware RTC

### ISSUE THREAD

**Issue by bluecmd** [u-root/u-root#982]
The `date` utility today is capable of setting the date and time of the system, but it does not persist it.

The normal way to interact with the hardware clock is using `hwclock` which most frequently interacts with `/dev/rtc0`.

Implementing a library that can sync the RTC with the system time would be useful for both the `date` utility and the `ntpdate` one.

**Comment by hugelgupf** [comment]
See #1085.
